# GitHub Pages configuration for Paste to Markdown

title: "Paste to Markdown"
description: "Convert rich text from your clipboard to Markdown format instantly"
# GitHub Pages will automatically set these based on repository
# url: auto-detected from repository
# baseurl: auto-detected from repository name

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude files from processing
exclude:
  - manifest.json
  - popup.html
  - popup.js
  - popup.css
  - background.js
  - content.js
  - create-icons.js
  - create-simple-icons.py
  - INSTALL.md
  - test.html
  - node_modules/
  - vendor/

# Include files that start with underscore
include:
  - _config.yml

# SEO and social
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Social links - GitHub Pages will auto-detect repository owner
# github_username: auto-detected from repository

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X
